Di string to latex
SprintCV-S24/frontend-SprintCV-S24 pull request #5
Opened 2024-03-02 19:38 UTC by DanaIzadpanah

Jack, this is a draft pull request!

2024-03-03 00:07 UTC, jackgarritano requested changes
Good job in general, I left comments on specific bugs.
Other general things that need to be added:
- I believe we're missing the functions for the skills section (see backend model and Jake's template)
- Right now each function is rendering a full page pdf. Because these are supposed to be individual items that will be dragged around, each pdf created by these functions needs to be only the size of the content, plus a little bit of vertial padding. I believe you can do this by adding a couple settings in the preamble, but you might find a different solution. If you do end up changing the preamble, pls create a separate preamble function, because the one you have right now is good for when we are generating the full resume pdf

2024-03-03 00:07 UTC, jackgarritano commented on src/latexUtils/latexString.ts
> +export interface ProjectType {
Projects also need to have the option to add a list of technologies. I updated the project type in the backend. You can copy that over and look at Jake's to see how projects are added

2024-03-03 00:07 UTC, jackgarritano commented on src/latexUtils/latexString.ts
> +export const generateProjectHeaderLatex = () => {
All of the generateHeader functions should be replaced with a single function that takes a string, since user will provide input for it

2024-03-03 00:07 UTC, jackgarritano commented on src/latexUtils/latexString.ts
> +    latexString += `\\resumeItemListStart\n`;
The test has a latex error here in Overleaf. If no bullets are provided, don't include \resumeItemListStart and \resumeItemListEnd

2024-03-03 00:07 UTC, jackgarritano commented on src/latexUtils/latexString.ts
> +    latexString += `\\begin{document}\n\\resumeSubheading{${sanitize(activityObj.title)}}{${sanitize(activityObj.subtitle)}}{${sanitize(activityObj.location)}}{${sanitize(activityObj.date)}}
Need \resumeSubHeadingListStart and \resumeSubHeadingListEnd; horizontal spacing is wrong and there is a latex error if you don't have it. Having it on every item does mess up vertical spacing a little, but hopefully that can be fixed when you make it so each pdf is only the size of the content then manually add vertical spacing. If that doesn't fix it, we will need to mess with the resumeSubHeadingListStart and end commands to make them work

2024-03-04 19:00 UTC, DanaIzadpanah commented on src/latexUtils/latexString.ts
> +export interface ProjectType {
okay :)

2024-03-04 20:40 UTC, jackgarritano commented
> Good job in general, I left comments on specific bugs. Other general things that need to be added:
> 
> * I believe we're missing the functions for the skills section (see backend model and Jake's template)
> * Right now each function is rendering a full page pdf. Because these are supposed to be individual items that will be dragged around, each pdf created by these functions needs to be only the size of the content, plus a little bit of vertial padding. I believe you can do this by adding a couple settings in the preamble, but you might find a different solution. If you do end up changing the preamble, pls create a separate preamble function, because the one you have right now is good for when we are generating the full resume pdf

Btw here is a better written out soln for rendering the pdfs at the height of the content

In separate preamble function:
- Add this after the last \usepackage:
```
\usepackage[
        top=0in,
        left=1in, right=1in, bottom=1in]{geometry}
```
- Delete this line:
```
\setlength{\topmargin}{0pt}
```
- Add this at the end of preamble:
```
\AtBeginDocument{
  \setbox0=\vbox\bgroup
  \preto\enddocument{\egroup
    \dimen0=\dp0
    \pdfpageheight=\dimexpr\ht0+\dimen0 % Sets the page height exactly to the content's height
    \unvbox0\kern-\dimen0 }
}
```

At end of each generate function, add this right before \end:
```
\vspace{-\lastskip}
```

2024-03-06 17:54 UTC, jackgarritano approved these changes
Cleaned it up, lgtm

2024-03-06 18:23 UTC, merged